version: '3.4'

services:
  todoui:
    #image: ${DOCKER_REGISTRY-}todoui
    build: ./TodoUI/
    ports:
        - 80:80
    depends_on:
        - todowebapi

  todowebapi:
    #image: ${DOCKER_REGISTRY-}todowebapi
    build: ./TodoWebAPI/
    ports:
        - 8081:80
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Admin123!"
        ACCEPT_EULA: "Y"
    
  seq-logger:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
